repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings
  private: public
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true

  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false

branches:
#   - name: main
#     protection:
#       required_pull_request_reviews: true
#         required_approving_review_count: 1
#         dismiss_stale_reviews: true
#         require_code_owner_reviews: false
#         dismissal_restrictions:
#           users: []
#           teams: []
#        required_status_checks:
#         strict: true
#         contexts: []
#       enforce_admins: true
#       required_linear_history: true
#       restrictions: null
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
